pnpm/pacquet

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/commands.rs, crates/cli/src/lib.rs, crates/cli/src/main.rs, crates/registry/Cargo.toml, crates/registry/src/error.rs, crates/registry/src/lib.rs, crates/registry/src/package.rs, crates/tarball/Cargo.toml, crates/tarball/src/lib.rs
Okay! So! Here I am!
The very first thing I want to say is, this code was already really great. If you were a random beginner who asked me to look at their code, I would say "great job" and not offer any of this feedback unless they were looking to actively level up at Rust. And while we don't know each other well, I do know that you're an experienced systems programmer, *and* looking to level up your Rust.
So I went a little extra. Sorry not sorry.
Each of these commits tells a story, in order. I left detailed commit messages. Some code gets re-written multiple times, but each step should be instructive, so if you only look at the final diff, you won't learn everything. Please take what you want, and throw away what you don't. And I am happy to discuss anything about any of this in …
=> Some feedback

.cargo/config.toml, Cargo.lock, Cargo.toml, README.md, crates/cli/src/lib.rs, crates/registry/Cargo.toml, crates/registry/src/error.rs, crates/registry/src/lib.rs, crates/registry/src/package.rs, crates/registry/src/package_name.rs, crates/registry/src/version_pin.rs, crates/tarball/Cargo.toml, crates/tarball/src/error.rs, crates/tarball/src/lib.rs, crates/tarball/src/symlink.rs
=> start implementing dependencies of dependency

crates/cli/src/lib.rs, crates/package_json/src/error.rs, crates/package_json/src/lib.rs, crates/registry/src/lib.rs, crates/tarball/src/lib.rs
Previously, package.json serializer removed unknown attributes. We now use a serde_json::Value to define the value and store the reference to it.
=> fix: improve package.json serialization

crates/cli/src/commands.rs, crates/cli/src/lib.rs, crates/package_json/src/lib.rs, crates/registry/src/lib.rs
One caveat is if a package already exists in another dependecy group, we don't remove the existing entry. Can we fix it in another PR?
=> feat: implement -D, -O options for add command

Cargo.lock, Cargo.toml, README.md, crates/cli/Cargo.toml, crates/cli/src/lib.rs, crates/cli/src/main.rs, crates/npmrc/Cargo.toml, crates/npmrc/src/custom_deserializer.rs, crates/npmrc/src/lib.rs, crates/registry/Cargo.toml, crates/registry/src/http_client.rs, crates/registry/src/lib.rs
I still need to add it to `cli` crate and use the values from crate, but opening it early to receive feedback
=> feat: add `.npmrc` file support

crates/npmrc/src/custom_deserializer.rs, crates/npmrc/src/lib.rs
I think env should without `$` symbols.
`$` just for us to use it with bash.For example
```bash
echo $HOME
```
In rust , we should use it with these code:
```rs
let home = env::var('HOME')
```
=> fix: store_dir envs should without $ symbols

.github/workflows/ci.yml, .github/workflows/codecov.yml, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/lib.rs, crates/npmrc/Cargo.toml, crates/npmrc/src/lib.rs, crates/package_json/Cargo.toml, crates/package_json/src/lib.rs, crates/registry/Cargo.toml, crates/tarball/Cargo.toml, crates/tarball/src/lib.rs
This PR simplifies test folder creation and improves test coverage in several places
=> test: improve test coverage

benchmark/.npmrc, benchmark/.yarnrc.yml, benchmark/add.sh, benchmark/bunfig.toml
An initial pretty simplistic benchmark that uses verdaccio (to remove the overhead of http requests to npm registry).
```
Benchmark 1: pacquet
Time (mean ± σ):     364.6 ms ±  21.1 ms    [User: 44.0 ms, System: 173.1 ms]
Range (min … max):   337.3 ms … 406.7 ms    10 runs
Benchmark 2: pnpm
Time (mean ± σ):     945.9 ms ±  43.4 ms    [User: 585.6 ms, System: 1491.7 ms]
Range (min … max):   876.5 ms … 1003.7 ms    10 runs
Benchmark 3: yarn
Time (mean ± σ):     610.5 ms ±   7.5 ms    [User: 1250.2 ms, System: 181.2 ms]
Range (min … max):   601.8 ms … 624.2 ms    10 runs
Benchmark 4: bun
Time (mean ± σ):      1.055 s ±  0.222 s    [User: 0.079 s, System: 0.306 s]
Range (min … max):    0.733 s …  1.550 s    10 runs
Summary
pacquet ran
1.67 ± 0.10 times faster than yarn
2.59 ± 0.19 times faster …
```
=> feat: add initial benchmark

crates/cli/src/commands.rs, crates/cli/src/lib.rs, crates/executor/src/lib.rs
Until now pacquet just ran any script/shell commands by just directly passing the entire command to `Command::new`. As per the std, `Command::new` takes only the file/program name, and any additional args need to be provided via the `arg` or `args` method.
Well now, i just touched it a little bit, to run `sh -c` and pass the actual command/script to it. This runs without any errors now, and sometimes scripts contain env vars too. For example
```json
{
"scripts": {
"test": "KEY=VALUE node index.js"
}
}
```
Now it is passed as `sh -c "KEY=ENV node index.js`. This seems to be how the peeps do it in pnpm. ([in pn](https://github.com/pnpm/pn/blob/8ed5abaaa90e3dcae783f763cdad3e289dbaca5e/src/main.rs#L111))
And also pass any sort of additional args provided in the run command to the script. For …
=> fix pacquet executer

Cargo.lock, Cargo.toml, crates/cafs/src/lib.rs, crates/package_manager/Cargo.toml, crates/package_manager/src/package_import.rs, crates/tarball/src/lib.rs
This slightly improves the performance for certain platforms
=> feat: add fs copy-on-write support

crates/cli/README.md, crates/cli/src/commands.rs, crates/cli/src/lib.rs, crates/package_manager/src/commands/install.rs
Thanks @Yakiyo for reporting the lack of error messages. This would make finding the root cause of the error faster, I assume.
```
➜  pacquet git:(error-reporting) ✗ cargo run -- init
Compiling pacquet_cli v0.0.1 (/Users/yagiz/Developer/pacquet/crates/cli)
Finished dev [unoptimized + debuginfo] target(s) in 0.78s
Running `target/debug/pacquet init`
Error: pacquet_package_json::already_exist_error
× initialize package.json
╰─▶ package.json file already exists
help: Your current working directory already has a package.json file.
```
=> feat: add better error reporting

crates/registry/src/package.rs
In this PR, I have replaced the usage of tokio mutex with std mutex in the codebase. This change improves the synchronization mechanism by utilizing the standard Rust mutex from the std library
İssue: https://github.com/anonrig/pacquet/issues/15
=> perf: replace tokio mutex with std mutex

crates/lockfile/src/lib.rs, crates/lockfile/src/package.rs, crates/registry/src/package.rs, crates/registry/src/package_distribution.rs, crates/registry/src/package_version.rs
`alias` is actually different from `rename`: `rename` changes the name, but there's still only one name. `alias` however adds another name, and when serde serializes the type to JSON, it will not choose the alias.
=> refactor: replace `alias` with `rename_all`

Cargo.lock, Cargo.toml, crates/cafs/Cargo.toml, crates/cafs/src/lib.rs, crates/cli/Cargo.toml, crates/cli/src/commands/add.rs, crates/cli/src/commands/install.rs, crates/cli/src/package.rs, crates/npmrc/Cargo.toml, crates/npmrc/src/custom_deserializer.rs, crates/npmrc/src/lib.rs, crates/package_json/Cargo.toml, crates/package_json/src/lib.rs, crates/registry/Cargo.toml, crates/registry/src/package.rs, crates/tarball/Cargo.toml, crates/tarball/src/lib.rs
for better error messages (with diffs) in case of test failure.
=> test: use pretty_assertions

Cargo.lock, Cargo.toml, tasks/benchmark/Cargo.toml, tasks/benchmark/src/main.rs
There is no reason to use 2 argument parsers in one project.
=> refactor: remove pico_args

crates/cli/src/package.rs, crates/registry/src/package_distribution.rs, crates/tarball/src/lib.rs
This is a temporary fix to make benchmarking with pnpm possible. /cc @zkochan 
Related to https://github.com/pnpm/pacquet/issues/108 and https://github.com/pnpm/pacquet/issues/100.
=> fix: install more packages without panics

Cargo.lock, crates/cli/src/commands/add.rs, crates/cli/src/commands/install.rs, crates/cli/src/lib.rs, crates/cli/src/package.rs, crates/cli/src/package_manager.rs, crates/npmrc/Cargo.toml, crates/npmrc/src/lib.rs, crates/tarball/src/lib.rs, tasks/benchmark/Cargo.toml, tasks/benchmark/src/main.rs
By leaking `Npmrc`, all its data become `'static`, allowing `store_dir` to be passed to another thread without `.clone()`.
Closes https://github.com/pnpm/pacquet/pull/101
=> feat: leak Npmrc, remove cloning

crates/cli/src/package.rs, crates/tarball/src/lib.rs, tasks/benchmark/src/main.rs
This fixes the "failed to lookup address information: nodename nor servname provided, or not known" error that happens on macOS.
=> fix: share the http client between requests

crates/tarball/src/lib.rs
@zkochan Can you test this with the `package.json` you used for https://github.com/pnpm/pacquet/pull/123 ?
=> feat: panic for programmer error, more diagnostics, remove duplicated map lookup

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/commands/install.rs, crates/cli/src/fs.rs, crates/npmrc/src/custom_deserializer.rs
Bump the `reflink-copy` dependency version to `0.1.8` as it supports now Copy-on-Write on the new Windows Dev Drives.
Keeping it as draft for now until I can test it in a Dev Drive later today.
Reference: [https://github.com/cargo-bins/reflink-copy/pull/28](https://github.com/cargo-bins/reflink-copy/pull/28)
=> feat: add support for CoW in Win Dev Drives

.github/workflows/micro-benchmark.yml
I forgot to change the CI when I remove `micro-benchmark` from `.cargo/config.toml`.
And since it was expected for the CI to fail, I didn't bother to check the error message.
=> fix(ci): micro-benchmark

.cargo/config.toml, .github/workflows/ci.yml, crates/cli/src/fs.rs, crates/npmrc/src/custom_deserializer.rs, justfile, tasks/integrated-benchmark/src/work_env.rs
Fixes https://github.com/pnpm/pacquet/issues/152
I also remove `ck` and `lint` from cargo aliases. Currently, `pacquet` doesn't use any feature flag, and even if we are to add them in the future, we would have to use cargo-hack instead.
=> ci: clippy and doc on all platforms

tasks/integrated-benchmark/src/cli_args.rs, tasks/integrated-benchmark/src/main.rs, tasks/integrated-benchmark/src/verdaccio.rs
With the `--verdaccio` flag, an instance of `verdaccio` will automatically be spawned if local registry doesn't respond.
=> feat(benchmark): auto launching verdaccio

.github/workflows/ci.yml, .taplo.toml, Cargo.toml, crates/fs/Cargo.toml, crates/lockfile/Cargo.toml, crates/testing-utils/Cargo.toml
* Add `taplo` to CI.
* Add `allow_blank_lines = 1` to taplo config.
=> ci: add taplo

.github/workflows/ci.yml
Just a few seconds ago, when CI for https://github.com/pnpm/pacquet/pull/166 was being run, `typos` [errored](https://github.com/pnpm/pacquet/actions/runs/6723936052/job/18275105882?pr=166). This is due to `typos` pushing commits to `master` before its binary has been uploaded to the release page, and my CI run just happens to coincide with this narrow window of time. In order to prevent unnecessary confusion in the future, I propose pinning typos to a fixed released version.
=> ci: pin typos version

crates/cli/tests/_utils.rs, crates/cli/tests/init.rs, crates/cli/tests/install.rs, crates/cli/tests/pnpm_compatibility.rs, crates/cli/tests/store.rs, crates/testing-utils/src/bin.rs
* It was ambiguous to pass a `bool` argument to a function.
* The tuples were terrible:
- The returning tuples were too long.
- The members inside the tuples share type, leading to ambiguity.
* The path to store dir was calculated downstream.
=> refactor: rewrite the `bin` functions into a struct

Cargo.lock, crates/lockfile/Cargo.toml, crates/lockfile/src/resolution.rs, crates/package-manager/src/install_package_by_snapshot.rs, crates/registry/Cargo.toml, crates/registry/src/package_distribution.rs, crates/tarball/src/lib.rs, tasks/micro-benchmark/Cargo.toml, tasks/micro-benchmark/src/main.rs
The parsing of integrity has been moved from tarball to serde.
=> refactor: parse integrity eagerly

Cargo.lock, crates/package-manager/Cargo.toml, crates/package-manager/src/install.rs, crates/package-manager/src/snapshots/pacquet_package_manager__install__tests__should_install_dependencies.snap
I forgot that the workspace member `package-manager` also has a test that relies on the registry.
=> test(lib): use registry-mock

Cargo.lock, Cargo.toml, crates/lockfile/src/pkg_name_suffix.rs
Closes https://github.com/pnpm/pacquet/pull/207
=> chore(cargo): bump `derive_more` to beta.6

crates/cli/tests/install.rs, crates/package-manager/src/create_cas_files.rs, crates/package-manager/src/create_virtual_dir_by_snapshot.rs, crates/tarball/src/lib.rs
Initially, the use of `OsString` was to allow non-UTF8 paths. However, the index file feature requires `serde` which in turns require UTF-8 to serialize. So the need for `OsString` ceases to be necessary, and removing it open new opportunities for some micro-optimizations.
=> refactor: use utf8 strings as mem cache keys
